--[[
  bee_files.lua -- the SINGLE SOURCE OF TRUTH for which files the drone needs.

  installer.lua and updater.lua both load this manifest instead of each keeping
  their own hardcoded list. Those two lists drifted apart once already (the
  installer's list was never updated as modules were added, so a fresh install
  pulled bee_keeper_manager.lua but none of its new dependencies and crashed with
  "module 'bee_mutation_graph' not found"). With one shared list that can't happen.

  bee_files_test.lua asserts `code` is CLOSED under require -- every bee_* module
  any shipped file requires is itself shipped -- so adding a new module without
  listing it here fails the test instead of the drone.

  Categories:
    code      -- Lua the drone runs; always (re)downloaded.
    data      -- static dumps (mutation graph / species / templates); always downloaded.
    preserved -- USER data: a default is fetched only if absent, and NEVER
                 overwritten by the updater (your config + your area scan).
--]]

return {
  code = {
    -- entry point + core
    "bee_keeper_manager_run.lua",
    "bee_keeper_manager.lua",
    "bee_breeding.lua",
    "bee_trait_config.lua",
    "bee_keeper_nav.lua",
    "bee_keeper_setup.lua",
    "bee_keeper_status.lua",
    "bee_keeper_ui.lua",
    "bee_trace.lua",
    -- mutation / genebank / program subsystems
    "bee_mutation_graph.lua",
    "bee_genebank.lua",
    "bee_genebank_scheduler.lua",
    "bee_rainbow.lua",
    "bee_traitmax_mutation.lua",
    "bee_traitmax.lua",
    "bee_program.lua",
    "bee_combine.lua",
    "bee_pool.lua",
    "bee_allele_values.lua",
    "bee_templates.lua",
    -- install/update machinery + this manifest (kept fresh via self-update)
    "bee_files.lua",
    "installer.lua",
    "updater.lua",
    "version.lua",
  },

  data = {
    -- Real GTNH mutation graph + species list, dumped once from a stationary
    -- Adapter next to an apiary (see docs/oc_forestry_api.md). Shipped as static
    -- data since the robot has no bee_housing component of its own.
    "bee_mutations.dat",
    "bee_species.dat",
    -- Per-species DEFAULT allele templates parsed from the mod source repos
    -- (see docs/data_sources.md) -- the fuel for traitmax-via-mutation.
    "bee_templates.dat",
  },

  preserved = {
    -- Default fetched only if missing; never overwritten by the updater.
    "bee_keeper_manager_config.lua",
    -- Generated by bee_keeper_setup.lua on first run (no repo default to fetch).
    "bee_keeper_sites.dat",
  },
}
