--[[
  Installer for the bee_serious drone. Pattern adapted from
  Level-Maintainer's installer.lua (github.com/Armagedon13/Level-Maintainer)
  -- known-working wget-based install + config-preservation approach.

  Run on the drone with:
    wget https://raw.githubusercontent.com/JosephKan3/bee_serious/main/installer.lua && installer
--]]

local shell = require("shell")
local filesystem = require("filesystem")

local repo = "https://raw.githubusercontent.com/JosephKan3/bee_serious/"
local branch = "main"

-- Production files the drone actually needs to run. Deliberately excludes:
--   - beeManager.lua/beeManager.config (the old transposer-network manager,
--     superseded by bee_keeper_manager.lua's drone-based design)
--   - *_test.lua (dev-time tests, run on a local Lua install, not the drone)
local files = {
  "bee_breeding.lua",
  "bee_trait_config.lua",
  "bee_keeper_nav.lua",
  "bee_keeper_setup.lua",
  "bee_keeper_status.lua",
  "bee_keeper_ui.lua",
  "bee_keeper_manager.lua",
  "bee_keeper_manager_run.lua",
  "updater.lua",
  "version.lua",
}

print("Installing bee_serious...")

-- Download all files
for _, file in ipairs(files) do
  local url = repo .. branch .. "/" .. file
  local path = shell.getWorkingDirectory() .. "/" .. file

  if filesystem.exists(path) then
    filesystem.remove(path)
  end

  print("Downloading " .. file .. "...")
  shell.execute("wget -fq " .. url .. " " .. path)
end

-- Config and the persisted area-scan file are user data -- never
-- overwritten if they already exist (e.g. a reinstall after an update).
local preserved = {
  "bee_keeper_manager_config.lua",
  "bee_keeper_sites.dat",
}

for _, file in ipairs(preserved) do
  local path = shell.getWorkingDirectory() .. "/" .. file
  if not filesystem.exists(path) then
    if file:match("%.lua$") then
      print("Downloading default " .. file .. "...")
      shell.execute("wget -fq " .. repo .. branch .. "/" .. file .. " " .. path)
    end
    -- bee_keeper_sites.dat has no repo default -- it's generated by
    -- bee_keeper_setup.lua on first run, not downloaded.
  else
    print(file .. " already exists - preserved")
  end
end

print("\nInstallation complete!")
print("Run 'bee_keeper_manager_run' to start (add 'ui' to show the live dashboard).")
